version: "2"
services:
  web:
    build: ./docker/web
    ports:
      - "8000:8000"
    links:
      - db
    volumes:
      - ./:/code
    working_dir: /code
    command: php artisan serve --host=0.0.0.0
    container_name: web
  db:
    image: "mysql:5.7"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      # If you want to set mysql user manually, remove these comments:
      MYSQL_DATABASE: report
      MYSQL_USER: developer
      MYSQL_PASSWORD: MySQL5.7
      MYSQL_HOST: ""
    mem_limit: 1000000000
    ports:
      - "3306:3306"
    container_name: db
